{% set name = "anybadge" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anybadge-{{ version }}.tar.gz
  sha256: 1dd61219b1ab65f8535002839fba12b0b04c56417fc5ca72c0aa598577de0e04

build:
  entry_points:
    - anybadge=anybadge:main
    - anybadge-server=anybadge_server:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.4

  run:
    - packaging
    - python >=3.4

test:
  imports:
    - anybadge
    - anybadge_server
  commands:
    - pip check
    - anybadge --help
    - anybadge-server --help
  requires:
    - pip

about:
  home: https://github.com/jongracecox/anybadge
  summary: Simple, flexible badge generator for project badges.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
