{% set name = "anybadge" %}
{% set version = "1.15.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/anybadge-{{ version }}.tar.gz
  sha256: 4c9696f4c12c8f1461311b5c7f1eb5287cb444cb9f7231fe9a0e810e4dce2c93

build:
  entry_points:
    - anybadge=anybadge.cli:main
    - anybadge-server=anybadge.server.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - packaging
    - python >={{ python_min }}

test:
  imports:
    - anybadge
    - anybadge_server
  commands:
    - pip check
    - anybadge --help
    - anybadge-server --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jongracecox/anybadge
  summary: Simple, flexible badge generator for project badges.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
